### ISSUE TITLE
可否介绍windows下编译ipfs的代理如何配置

### ISSUE THREAD

**Issue by throne-developer** [xipfs/IPFS-Internals#1]
ipfs源码编译需要gx工具和科学上网，可否详细介绍具体步骤

**Comment by xcshuan** [comment]
目前IPFS已经改用gomod，可以使用微软地代理。

**Comment by godcong** [comment]
set GOPROXY=https://goproxy.io
试试这个代理,速度还可以
现在编译没以前那么麻烦了
直接用go命令编译就行了

**Comment by xipfs** [comment]
现在很方便了。
